Repository FE13-part4-team4/coworkers, pull requests merged in 2025-04, with the labels that each got.

#10 [Style] globals css
  public/icons/icons.ts
  public/images/images.ts
  src/app/page.tsx
  src/assets/assets.tsx
  src/components/Button/Button.tsx
  src/hooks/hooks.tsx
  src/styles/globals.css
  src/types/types.tsx
  src/utils/utils.tsx
Labels: Style

#11 [Refactor] globals.css
  .github/workflows/main.yml
  src/app/page.tsx
  src/styles/globals.css
Labels: Refactor

#13 [Feat] 버튼 컴포넌트 작성 완료
  package-lock.json
  package.json
  public/icons/icons.ts
  src/app/layout.tsx
  src/assets/icons/IconCheck.tsx
  src/assets/icons/IconPlus.tsx
  src/components/Button/Button.tsx
  src/styles/globals.css
Labels: Feat

#14 [Feat] Input
  .github/workflows/main.yml
  public/icons/arrow_up.svg
  public/icons/initialprofile.svg
  public/icons/kebab.svg
  public/icons/toggle.svg
  public/icons/visibility_off.svg
  public/icons/visibility_on.svg
  src/components/Inputs/Inputs.tsx
  src/components/ReplyItem.tsx
  src/types/inputtypes.tsx
  src/types/types.tsx
Labels: Feat, Refactor

#15 [Chore] Issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/todo.md
Labels: Chore

#16 [Chore] Issue templates 적용
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/todo.md
  .github/workflows/main.yml
Labels: Chore

#21 [Feat] Component : Card - 댓글
  src/app/page.tsx
  src/assets/icons/IconHeart.tsx
  src/components/Card/Comment/AddComment.tsx
  src/components/Card/Comment/AuthorInfo.tsx
  src/components/Card/Comment/BoardComment.tsx
  src/styles/globals.css
Labels: Feat

#23 [Feat] Header, SideMenu
  public/icons/close.svg
  public/icons/gnb_menu.svg
  public/icons/logo_lg.svg
  public/icons/logo_sm.svg
  public/icons/profile.svg
  public/img_team.png
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Inputs/Inputs.tsx
  src/components/dropdown/BaseDropdown.tsx
  src/components/dropdown/DropDownOpenBtn.tsx
  src/components/dropdown/GroupList.tsx
  src/components/dropdown/Groups.tsx
  src/components/dropdown/ProfileItem.tsx
  src/components/dropdown/ProfileItemList.tsx
  src/components/dropdown/SelectableDropdown.tsx
  src/components/layout/Gnb/Header.tsx
  src/components/layout/Gnb/HeaderContext.tsx
  src/components/layout/Gnb/Logo.tsx
  src/components/layout/Gnb/ProfileSelector.tsx
  src/components/layout/Gnb/SideMenu.tsx
  src/components/layout/Gnb/TeamSelector.tsx
  src/components/layout/layout.tsx
Labels: Feat, Refactor

#25 [Feat] Modal 공통 컴포넌트 기본 UI 및 기능 구현
  public/icons/alert.svg
  src/app/page.tsx
  src/components/common/Modal/ModalButtons.tsx
  src/components/common/Modal/ModalHeader.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Modal/style.ts
  src/components/common/Modal/types.ts
  src/hooks/hooks.tsx
  src/hooks/useModal.ts
Labels: Feat

#26 [Feat] Components for teampage
  package-lock.json
  package.json
  public/icons/done.svg
  public/icons/gear.svg
  public/icons/initialprofile.svg
  public/icons/initialteamprofile.svg
  public/icons/pencil.svg
  public/icons/teamheader_decoration.svg
  src/components/common/Inputs.tsx
  src/components/common/Profiles.tsx
  src/components/common/ReplyItem.tsx
  src/components/common/TaskElements.tsx
  src/components/common/TeamHeader.tsx
  src/hooks/useClickOutside.ts
  src/hooks/useValidatedInput.ts
  src/styles/trimColors.ts
  src/types/inputtypes.tsx
  src/types/profiletypes.tsx
  src/types/tasktypes.tsx
  src/utils/stringToHash.ts
  src/utils/utils.tsx
Labels: Feat, Refactor

#30 [Chore] Set up page structure
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(main)/[teamid]/[taskid]/page.tsx
  src/app/(main)/[teamid]/page.tsx
  src/app/(main)/[teamid]/tasklist/page.tsx
  src/app/(main)/addteam/page.tsx
  src/app/(main)/boards/page.tsx
  src/app/(main)/myhistory/page.tsx
  src/app/(main)/mypage/page.tsx
Labels: Chore

#28 [Fix, Refator] Gnb
  public/icons/check.svg
  src/app/page.tsx
  src/components/dropdown/DropDownOpenBtn.tsx
  src/components/layout/Gnb/HeaderContext.tsx
  src/components/layout/Gnb/Headerconfig.ts
Labels: Fix, Feat, Refactor

#31 [Feat] Component : Card - 상세
  package-lock.json
  package.json
  src/components/Card/Comment/AuthorInfo.tsx
  src/components/Card/Comment/BoardComment.tsx
  src/components/Card/Post/Deatil/DateInfo.tsx
  src/components/Card/Post/Deatil/DetailPost.tsx
  src/components/Card/Post/PostDropdown.tsx
  src/components/Card/SlideWrapper.tsx
  src/components/dropdown/BaseDropdown.tsx
Labels: Feat

#34 [Feat] Landing page
  public/images/images.ts
  public/images/landing-bottom-large.png
  public/images/landing-bottom-medium.png
  public/images/landing-bottom-small.png
  public/images/landing-section1.png
  public/images/landing-section2.png
  public/images/landing-section3.png
  public/images/landing-top-large.png
  public/images/landing-top-medium.png
  public/images/landing-top-small.png
  src/app/page.tsx
  src/assets/icons/Done.tsx
  src/assets/icons/Folder.tsx
  src/assets/icons/Message.tsx
  src/assets/icons/Repair.tsx
  src/components/landing/LandingBody.tsx
  src/components/landing/LandingFooter.tsx
  src/components/landing/LandingHeader.tsx
  src/components/landing/index.tsx
  src/components/layout/Gnb/Headerconfig.ts
  src/styles/globals.css
Labels: Fix, Feat

#36 [Feat] 팀 생성하기, 팀 참여하기 Beta 0.1
  public/icons/checkbox_default.svg
  src/app/(main)/addteam/page.tsx
  src/components/List/todo.tsx
Labels: Feat

#38 [Refactor] 루트 레이아웃 구조 변경 (Header, Sidemenu)
  src/app/layout.tsx
  src/app/page.tsx
  src/components/layout/ClientHeaderLayout.tsx
Labels: Refactor

#40 [Feat] 할 일 만들기 모달
  package-lock.json
  package.json
  src/app/layout.tsx
  src/assets/icons/IconArrowPolygon.tsx
  src/components/TodoFullCreateModal/DatePickerCalender.tsx
  src/components/TodoFullCreateModal/DatePickerInput.tsx
  src/components/TodoFullCreateModal/index.tsx
  src/components/TodoFullCreateModal/style.css
Labels: Feat

#41 [Feat] Add the action menu on the teampage for administrator
  package-lock.json
  src/app/(main)/[teamid]/page.tsx
  src/components/Report.tsx
  src/components/common/ActionMenu.tsx
  src/components/common/Inputs.tsx
  src/components/common/Member.tsx
  src/components/common/Profiles.tsx
  src/components/common/TaskElements.tsx
  src/components/common/TeamHeader.tsx
  src/types/actionmenutypes.ts
  src/utils/regex.ts
Labels: Feat
