Repository FE13-part4-team4/coworkers, pull requests merged in 2025-05, with the labels that each got.

#45 [Feat Fix] Login, signup, reset password Page
  src/app/(auth)/login/page.tsx
  src/app/(auth)/resetpassword/page.tsx
  src/app/(auth)/signup/page.tsx
  src/components/ResetPw.tsx
  src/components/common/Inputs.tsx
  src/components/landing/index.tsx
  src/components/oauth/OAuthBtn.tsx
  src/components/oauth/index.tsx
Labels: Fix, Feat

#47 [Feat] Myhistory page UI
  src/app/(main)/[teamid]/page.tsx
  src/app/(main)/myhistory/page.tsx
  src/components/MyHistoryByDate.tsx
  src/components/common/MyHistoryItem.tsx
  src/types/myhistorytypes.ts
  src/utils/date.ts
Labels: Feat

#46 [Feat] Page : 자유게시판, 자유게시판 상세
  public/icons/comment.svg
  public/icons/search.svg
  src/app/(main)/boards/[articleid]/page.tsx
  src/app/(main)/boards/create/page.tsx
  src/app/(main)/boards/page.tsx
  src/components/Card/CardType.ts
  src/components/Card/Comment/AuthorInfo.tsx
  src/components/Card/Comment/BoardComment.tsx
  src/components/Card/Post/BestPost.tsx
  src/components/Card/Post/GeneralPost.tsx
  src/components/Card/Post/PostCard.tsx
  src/components/Card/testPosts.ts
  src/components/layout/Gnb/Headerconfig.ts
Labels: Feat

#49 [Feat] Mypage UI
  public/icons/secession.svg
  src/app/(main)/mypage/AccountDeleteButton.tsx
  src/app/(main)/mypage/CurrentEmailSection.tsx
  src/app/(main)/mypage/EditableNameSection.tsx
  src/app/(main)/mypage/EditablePasswordSection.tsx
  src/app/(main)/mypage/EditableProfileSection.tsx
  src/app/(main)/mypage/page.tsx
  src/app/(main)/mypage/types.ts
  src/components/common/Inputs.tsx
  src/components/layout/Gnb/Headerconfig.ts
  src/styles/globals.css
Labels: Feat

#52 [Feat] Button
  src/app/(auth)/resetpassword/page.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Modal/index.tsx
Labels: Fix, Feat

#51 [Feat] Page : 자유게시판 - 글쓰기 + Component : ArrowDropdown
  public/icons/down_arrow.svg
  src/app/(main)/boards/[articleid]/edit/page.tsx
  src/app/(main)/boards/[articleid]/page.tsx
  src/app/(main)/boards/best/page.tsx
  src/app/(main)/boards/create/page.tsx
  src/app/(main)/boards/new/page.tsx
  src/app/(main)/boards/page.tsx
  src/components/Card/CardType.ts
  src/components/Card/Comment/AuthorInfo.tsx
  src/components/Card/ImgUpload.tsx
  src/components/Card/Post/PostCard.tsx
  src/components/common/ArrowDropdown.tsx
  src/hooks/useWindowSize.tsx
Labels: Feat

#55 [Feat] Sub pages on the Team page (edit, no-team) / Header (동적라우트 설정)
  public/images/noTeam.svg
  src/app/(main)/[teamid]/edit/EditButton.tsx
  src/app/(main)/[teamid]/edit/EditableTeamNameSection.tsx
  src/app/(main)/[teamid]/edit/EditableTeamProfileSection.tsx
  src/app/(main)/[teamid]/edit/page.tsx
  src/app/(main)/noteam/page.tsx
  src/components/common/TeamHeader.tsx
  src/components/layout/Gnb/HeaderContext.tsx
  src/components/layout/Gnb/Headerconfig.ts
Labels: Feat

#53 [Feat] 리스트 페이지 Beta0.1
  public/icons/calendar.svg
  public/icons/type=left.svg
  public/icons/type=right.svg
  src/app/(main)/[teamid]/tasklist/page.tsx
  src/app/(main)/addteam/page.tsx
  src/app/(main)/join/page.tsx
  src/components/List/todo.tsx
  src/components/TodoFullCreateModal/index.tsx
  src/components/common/Inputs.tsx
Labels: Feat

#56 [Feat] Add modals and additional info display to the team page
  src/app/(main)/[teamid]/page.tsx
  src/app/(main)/myhistory/page.tsx
  src/assets/icons/Alert.tsx
  src/components/Report.tsx
  src/components/common/ActionMenu.tsx
  src/components/common/Inputs.tsx
  src/components/common/Member.tsx
  src/components/common/Toast.tsx
  src/components/myhistory/MyHistoryByDate.tsx
  src/components/myhistory/MyHistoryItem.tsx
  src/components/teampage/Report.tsx
  src/components/teampage/ReportProgress.tsx
  src/components/teampage/TaskElements.tsx
  src/components/teampage/TeamHeader.tsx
  src/hooks/useToast.ts
  src/hooks/useValidatedInput.ts
  src/types/inputtypes.tsx
  src/types/teampagetypes.tsx
  src/utils/regex.ts
Labels: Fix, Feat

#58 [Feat/Refactor] Modal / TodoFullCreateModal
  src/components/TodoFullCreateModal/DatePickerCalender.tsx
  src/components/TodoFullCreateModal/DatePickerInput.tsx
  src/components/TodoFullCreateModal/index.tsx
  src/components/TodoFullCreateModal/style.css
  src/components/common/ArrowDropdown.tsx
  src/components/common/Inputs.tsx
  src/components/common/Modal/ModalButtons.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Modal/style.ts
  src/styles/globals.css
Labels: Feat, Refactor

#61 [Feat] Teampage profile modal / useModalGroup 훅 생성
  src/app/(pages)/(main)/[teamid]/page.tsx
  src/components/common/Member.tsx
  src/hooks/useModal.ts
  src/hooks/useModalGroup.ts
  src/types/teampagetypes.tsx
Labels: Feat

#62 [Feat] 상세 카드 연결 + 코드 수정
  src/app/(pages)/(main)/[teamid]/tasklist/page.tsx
  src/app/(pages)/(main)/boards/[articleid]/page.tsx
  src/app/(pages)/(main)/boards/best/page.tsx
  src/app/(pages)/(main)/boards/page.tsx
  src/components/Card/CardType.ts
  src/components/Card/Comment/AuthorInfo.tsx
  src/components/Card/Comment/BoardComment.tsx
  src/components/Card/Post/Deatil/DetailPost.tsx
  src/components/Card/Post/PostCard.tsx
  src/components/Card/Post/PostDropdown.tsx
  src/components/Card/testPosts.ts
  src/components/common/Inputs.tsx
Labels: Feat, Refactor

#63 [Repact] 중복 폴더 삭제, 미사용 임포트문 삭제
  src/app/(pages)/(main)/[teamid]/tasklist/page.tsx
Labels: Refactor

#70 [Refactor] UI 수정
  src/app/(pages)/(main)/boards/[articleid]/page.tsx
  src/app/(pages)/(main)/boards/page.tsx
  src/components/Card/Post/BestPost.tsx
  src/components/Card/Post/GeneralPost.tsx
  src/components/Card/testPosts.ts
Labels: Refactor

#72 [Refactor] OAuthBtn / useAuthStore
  src/app/(pages)/(auth)/login/page.tsx
  src/app/(pages)/(auth)/login/signupForm.tsx
  src/app/layout.tsx
  src/components/InitializeAuth.tsx
  src/components/common/Inputs.tsx
  src/components/landing/LandingHeader.tsx
  src/components/oauth/OAuthBtn.tsx
  src/components/oauth/OAuthButton.tsx
  src/stores/useAuthStore.ts
  src/types/inputtypes.tsx
Labels: Refactor

#79 [Feat] 404 page
  src/app/not-found.tsx
Labels: Feat

#77 [Feat] login, signup, resetpassword
  src/app/(pages)/(auth)/login/page.tsx
  src/app/(pages)/(auth)/reset-password/page.tsx
  src/app/(pages)/(auth)/resetpassword/page.tsx
  src/app/(pages)/(auth)/signup/page.tsx
  src/app/(pages)/(auth)/signup/signupForm.tsx
  src/app/api/auth.ts
  src/components/landing/LandingHeader.tsx
  src/utils/regex.ts
Labels: Feat

#81 [Feat] 팀생성,참여 페이지, 추가 컴포넌트 및 분리
  .eslintrc.json
  package-lock.json
  package.json
  src/api/TeamCreate.ts
  src/app/(pages)/(main)/addteam/page.tsx
  src/app/(pages)/(main)/join/page.tsx
  src/components/FormField.tsx
  src/components/ProfileUploader.tsx
  src/hooks/useAddTeamForm.ts
  src/hooks/useJoinTeamForm.ts
Labels: Feat

#82 [Feat] header / dropdown
  public/team.png
  src/app/(pages)/(auth)/layout.tsx
  src/app/(pages)/(auth)/reset-password/page.tsx
  src/app/(pages)/layout.tsx
  src/app/api/axiosInstance.ts
  src/app/api/user.ts
  src/components/InitializeAuth.tsx
  src/components/dropdown/DropDownOpenBtn.tsx
  src/components/dropdown/Groups.tsx
  src/components/dropdown/ProfileItemList.tsx
  src/components/layout/ClientHeaderLayout.tsx
  src/components/layout/Gnb/Header.tsx
  src/components/layout/Gnb/HeaderContext.tsx
  src/components/layout/Gnb/Headerconfig.ts
  src/components/layout/Gnb/ProfileSelector.tsx
  src/components/layout/Gnb/SideMenu.tsx
  src/components/layout/Gnb/TeamSelector.tsx
  src/stores/useAuthStore.ts
  src/stores/useUserStore.ts
Labels: Feat

#83 [Refactor] Team page UI & input validations
  package-lock.json
  src/api/auth.ts
  src/api/axiosInstance.ts
  src/api/user.api.ts
  src/api/user.ts
  src/app/(pages)/(auth)/login/page.tsx
  src/app/(pages)/(auth)/reset-password/page.tsx
  src/app/(pages)/(auth)/signup/page.tsx
  src/app/(pages)/(auth)/signup/signupForm.tsx
  src/app/(pages)/(main)/[teamid]/page.tsx
  src/app/api/user.ts
  src/components/InitializeAuth.tsx
  src/components/common/Inputs.tsx
  src/components/common/Toast.tsx
  src/components/teampage/ReportProgress.tsx
  src/components/teampage/TeamHeader.tsx
  src/hooks/useCurrentUser.ts
  src/hooks/useToast.ts
  src/styles/globals.css
  src/types/inputtypes.tsx
  src/types/tasktypes.tsx
  src/types/usertypes.ts
  src/utils/regex.ts
Labels: Fix, Feat, Refactor

#86 [Feat] 자유게시판 - api 연결
  src/api/articles.ts
  src/app/(pages)/(main)/boards/[articleid]/edit/page.tsx
  src/app/(pages)/(main)/boards/[articleid]/page.tsx
  src/app/(pages)/(main)/boards/best/page.tsx
  src/app/(pages)/(main)/boards/new/page.tsx
  src/app/(pages)/(main)/boards/page.tsx
  src/components/Card/CardType.ts
  src/components/Card/Comment/AddComment.tsx
  src/components/Card/Comment/AuthorInfo.tsx
  src/components/Card/Comment/BoardComment.tsx
  src/components/Card/ImgUpload.tsx
  src/components/Card/Post/BestPost.tsx
  src/components/Card/Post/GeneralPost.tsx
  src/components/Card/Post/PostCard.tsx
  src/components/Card/Post/PostDropdown.tsx
  src/components/Card/testPosts.ts
  src/components/common/ArrowDropdown.tsx
  src/components/layout/Gnb/Header.tsx
  src/components/layout/Gnb/Headerconfig.ts
  src/constants/queryKeys.ts
Labels: Feat

#87 [Feat] 팀생성,참여 페이지
  src/api/TeamCreate.ts
  src/app/(pages)/(main)/addteam/page.tsx
  src/components/ProfileUploader.tsx
  src/hooks/useAddTeamForm.ts
Labels: Feat

#88 [Feat] Show group name on group page
  src/api/user.api.ts
  src/api/user.ts
  src/app/(pages)/(main)/[teamid]/page.tsx
  src/components/layout/Gnb/Headerconfig.ts
  src/components/teampage/TaskElements.tsx
  src/hooks/useCurrentUser.ts
  src/hooks/useGroupPageInfo.ts
  src/types/grouptypes.ts
  src/types/tasklisttypes.ts
  src/types/tasktypes.ts
  src/types/tasktypes.tsx
  src/types/teampagetypes.ts
  src/types/usertypes.ts
Labels: Fix, Feat

#89 [Feat] Mypage 기능 구현 (API)
  src/api/user.ts
  src/app/(pages)/(main)/mypage/components/AccountDeleteButton.tsx
  src/app/(pages)/(main)/mypage/components/EditableNameSection.tsx
  src/app/(pages)/(main)/mypage/components/EditablePasswordSection.tsx
  src/app/(pages)/(main)/mypage/types.ts
  src/components/common/Inputs.tsx
  src/types/inputtypes.tsx
Labels: Feat

#90 [Feat] 자유게시판 - api 연결2(게시글 수정, 좋아요)
  src/api/TeamCreate.ts
  src/api/user.ts
  src/app/(pages)/(main)/boards/[articleid]/page.tsx
  src/app/(pages)/(main)/boards/new/page.tsx
  src/app/layout.tsx
  src/components/Card/CardType.ts
  src/components/Card/Comment/AddComment.tsx
  src/components/Card/Comment/BoardComment.tsx
  src/components/Card/Post/PostCard.tsx
Labels: Feat

#92 [Feat] Integrate team page with API (partial)
  src/api/group.api.ts
  src/api/tasklist.api.ts
  src/api/user.api.ts
  src/app/(pages)/(main)/[teamid]/page.tsx
  src/components/myhistory/MyHistoryByDate.tsx
  src/components/teampage/Report.tsx
  src/components/teampage/TeamHeader.tsx
  src/hooks/useGroupDetail.ts
  src/hooks/useGroupPageInfo.ts
  src/types/tasklisttypes.ts
  src/types/teampagetypes.ts
  src/utils/date.ts
Labels: Feat

#93 [Feat, Fix] 카카오 로그인 및 헤더
  src/api/user.ts
  src/app/(pages)/(auth)/login/kakao/page.tsx
  src/app/(pages)/(main)/mypage/components/EditableNameSection.tsx
  src/app/layout.tsx
  src/components/InitializeAuth.tsx
  src/components/dropdown/BaseDropdown.tsx
  src/components/dropdown/SelectableDropdown.tsx
  src/components/layout/Gnb/Header.tsx
  src/components/layout/Gnb/SideMenu.tsx
  src/components/layout/Gnb/TeamSelector.tsx
  src/components/oauth/OAuthBtn.tsx
  src/constants/queryKeys.ts
  src/hooks/useAddTeamForm.ts
  src/hooks/useUserInfo.ts
  src/stores/useAuthStore.ts
  src/stores/useUserStore.ts
  src/types/usertypes.ts
Labels: Fix, Feat

#94 [Feat] Mypage form 검증 로직 추가
  src/app/(pages)/(main)/mypage/components/AccountDeleteButton.tsx
  src/app/(pages)/(main)/mypage/components/EditableNameSection.tsx
  src/app/(pages)/(main)/mypage/components/EditablePasswordSection.tsx
  src/components/common/Inputs.tsx
  src/types/inputtypes.tsx
Labels: Feat

#95 [Feat]
  src/api/group.api.ts
  src/api/tasklist.api.ts
  src/api/user.api.ts
  src/api/user.ts
  src/app/(pages)/(auth)/invite/page.tsx
  src/app/(pages)/(main)/[teamid]/page.tsx
  src/components/common/Inputs.tsx
  src/components/invite/InviteAcceptScreen.tsx
  src/components/invite/InviteAuthForm.tsx
  src/components/teampage/Report.tsx
  src/components/teampage/TaskElements.tsx
  src/hooks/useInvitePageInfo.ts
  src/hooks/useUserInfo.ts
  src/types/profiletypes.tsx
  src/types/tasktypes.ts
  src/types/teampagetypes.ts
  src/types/usertypes.ts
  src/utils/date.ts
  src/utils/inviteTokenDecoder.ts
Labels: Feat

#96 [Fix] Stop task detail effect loop
  src/app/(pages)/(main)/[teamid]/page.tsx
  src/components/teampage/Report.tsx
  src/hooks/useGroupPageInfo.ts
  src/types/teampagetypes.ts
Labels: Fix

#100 [Feat] No-team page 기능
  src/app/(pages)/(main)/[teamid]/TeamPage.tsx
  src/app/(pages)/(main)/[teamid]/page.tsx
  src/app/(pages)/(main)/noteam/page.tsx
Labels: Feat

#102 [Feat] Page : 리스트 - 할일 상세 모달 연결
  src/api/createTask.ts
  src/api/detailPost.ts
  src/app/(pages)/(main)/[teamid]/tasklist/components/TodoFullCreateModal/index.tsx
  src/app/(pages)/(main)/[teamid]/tasklist/page.tsx
  src/app/layout.tsx
  src/components/Card/CardType.ts
  src/components/Card/Comment/BoardComment.tsx
  src/components/Card/Post/Deatil/DateInfo.tsx
  src/components/Card/Post/Deatil/DetailPost.tsx
  src/components/Card/Post/PostDropdown.tsx
  src/components/List/todo.tsx
  src/components/common/ArrowDropdown.tsx
  src/components/common/Inputs.tsx
  src/context/TaskReloadContext.tsx
Labels: Feat

#105 [Feat] Group page task/member management enhancements
  public/icons/crown.svg
  src/api/group.api.ts
  src/api/tasklist.api.ts
  src/app/(pages)/(main)/[teamid]/TeamPage.tsx
  src/app/(pages)/(main)/[teamid]/edit/EditButton.tsx
  src/components/common/ActionMenu.tsx
  src/components/common/Member.tsx
  src/components/common/Modal/DeleteConfirmModal.tsx
  src/components/common/Modal/EditTaskListModal.tsx
  src/components/teampage/Report.tsx
  src/components/teampage/TaskElements.tsx
  src/components/teampage/TeamHeader.tsx
  src/types/actionmenutypes.ts
  src/types/tasktypes.ts
  src/types/teampagetypes.ts
Labels: Feat

#107 [Feat] Myhistory page (+Landing)
  package-lock.json
  src/api/user.ts
  src/app/(pages)/(main)/[teamid]/[taskid]/page.tsx
  src/app/(pages)/(main)/myhistory/components/TaskHistoryByDate.tsx
  src/app/(pages)/(main)/myhistory/components/groupTasksByDate.ts
  src/app/(pages)/(main)/myhistory/page.tsx
  src/assets/icons/Done.tsx
  src/components/landing/LandingHeader.tsx
  src/components/myhistory/MyHistoryByDate.tsx
  src/components/myhistory/MyHistoryItem.tsx
Labels: Feat

#108 [Feat] Add pagination and real-time updates to group page
  src/app/(pages)/(main)/[teamid]/TeamPage.tsx
  src/components/common/ActionMenu.tsx
  src/components/teampage/Report.tsx
  src/components/teampage/TaskElements.tsx
Labels: Fix, Feat

#109 [Feat/Refactor] My page (profile uploader) / My history (no data UI)
  src/api/user.ts
  src/app/(pages)/(main)/myhistory/page.tsx
  src/app/(pages)/(main)/mypage/components/EditableProfileSection.tsx
  src/app/(pages)/(main)/mypage/page.tsx
  src/components/layout/Gnb/Headerconfig.ts
  src/hooks/useEditProfileImage.ts
Labels: Feat, Refactor

#113 [Chore] 빌드오류 수정
  src/app/(pages)/(auth)/login/kakao/kakaoCallback.tsx
  src/app/(pages)/(auth)/login/kakao/page.tsx
  src/app/(pages)/(auth)/reset-password/ResetPasswordHandler.tsx
  src/app/(pages)/(auth)/reset-password/page.tsx
Labels: Chore

#119 [Feat] Dropdown, sideMenu
  src/components/dropdown/BaseDropdown.tsx
  src/components/dropdown/SelectableDropdown.tsx
  src/components/landing/LandingHeader.tsx
  src/components/layout/Gnb/ProfileSelector.tsx
  src/components/layout/Gnb/SideMenu.tsx
  src/components/layout/Gnb/TeamSelector.tsx
Labels: Fix, Feat

#122 [Refactor] Task : 시간/날짜/댓글 수 + kebab
  src/api/articles.ts
  src/app/(pages)/(main)/[teamid]/tasklist/components/TodoFullCreateModal/TodoEditModal.tsx
  src/app/(pages)/(main)/[teamid]/tasklist/components/TodoFullCreateModal/index.tsx
  src/app/(pages)/(main)/[teamid]/tasklist/page.tsx
  src/app/(pages)/(main)/boards/new/page.tsx
  src/components/Card/CardType.ts
  src/components/Card/Comment/AuthorInfo.tsx
  src/components/Card/Comment/BoardComment.tsx
  src/components/Card/Post/Detail/DetailPost.tsx
  src/components/Card/Post/PostCard.tsx
  src/components/Card/Post/PostDropdown.tsx
  src/components/List/todo.tsx
Labels: Refactor

#125 [Fix] 팀 참여로 팀페이지 진입시 헤더 팀드롭다운 반영안됨 수정
  src/app/(pages)/(main)/mypage/components/AccountDeleteButton.tsx
  src/components/layout/Gnb/Header.tsx
  src/hooks/useJoinTeamForm.ts
Labels: Fix, Feat

#126 [Fix] 모달 중복 해결
  src/app/(pages)/(main)/[teamid]/tasklist/components/TodoFullCreateModal/TodoEditModal.tsx
  src/app/(pages)/(main)/[teamid]/tasklist/components/TodoFullCreateModal/index.tsx
  src/app/(pages)/(main)/[teamid]/tasklist/page.tsx
  src/components/List/todo.tsx
Labels: Fix

#127 [Refactor] NoTeam page, Mypage, Myhistory, TodoFullCreateModal
  src/app/(pages)/(main)/[teamid]/edit/EditableTeamProfileSection.tsx
  src/app/(pages)/(main)/[teamid]/tasklist/components/TodoFullCreateModal/DatePickerTime.tsx
  src/app/(pages)/(main)/[teamid]/tasklist/components/TodoFullCreateModal/TodoEditModal.tsx
  src/app/(pages)/(main)/[teamid]/tasklist/components/TodoFullCreateModal/index.tsx
  src/app/(pages)/(main)/[teamid]/tasklist/components/TodoFullCreateModal/style.css
  src/app/(pages)/(main)/mypage/components/EditableProfileSection.tsx
  src/app/(pages)/(main)/noteam/NoTeam.tsx
  src/app/(pages)/(main)/noteam/page.tsx
Labels: Refactor

#131 [Refactor] 리스트 날짜 데이터 수정
  src/app/(pages)/(main)/[teamid]/tasklist/page.tsx
  src/components/List/todo.tsx
Labels: Refactor

#135 [feat] header, Landingpage 효과 추가
  src/components/landing/LandingHeader.tsx
  src/components/layout/Gnb/Header.tsx
  src/components/layout/Gnb/ProfileSelector.tsx
Labels: Fix, Feat

#136 [Chore] 불필요한 코드 삭제
  src/app/(pages)/(main)/boards/[articleid]/page.tsx
  src/app/(pages)/(main)/mypage/page.tsx
  src/app/(pages)/(main)/noteam/page.tsx
  src/components/Card/Comment/AddComment.tsx
  src/components/Card/Comment/BoardComment.tsx
  src/components/Card/ImgUpload.tsx
  src/components/Card/Post/Detail/DetailPost.tsx
  src/components/List/todo.tsx
Labels: Chore

#139 [Fix] console.log 삭제
  src/app/(pages)/(main)/boards/best/page.tsx
  src/app/(pages)/(main)/boards/new/page.tsx
  src/components/Card/Comment/BoardComment.tsx
Labels: Fix
